### ISSUE TITLE
forked, works for me: https://github.com/ohnonot/fluxStyle

### ISSUE THREAD

**Issue by ohnonot** [michaelrice/fluxStyle#7]
I made a few changes just to get it to work on my arch box, please see the [readme](https://github.com/ohnonot/fluxStyle/blob/development/README.md).

not sure if it should be a pull request, because all i know is that it works for me (and probably on archlinux in general).

**Comment by michaelrice** [comment]
Im not really interested in maintaining the code for this anymore. I only wrote it to help me learn python and pygtk like 10 years ago. Please feel free to run with the project how ever you see fit
