### ISSUE TITLE
distutils.core

### ISSUE THREAD

**Issue by tuxd3v** [michaelrice/fluxStyle#8]
Hello,
I to get module below in debian?
```lua
~/fluxStyle# ./setup.py install
Traceback (most recent call last):
  File "./setup.py", line 10, in <module>
    from distutils.core import setup
ModuleNotFoundError: No module named 'distutils.core'
```

Thanks in Advance,
Best Regards
tux

**Comment by michaelrice** [comment]
I originally wrote this in 2004 or 2005, its cool to see someone found it and is trying to use it.. To make this work Im guessing you need like python 2.x but i have no idea if this still works or not..
